import Link from "next/link";

// Content structure follows the Security and Data Privacy Document
// section 12's required 10-point outline exactly. Every fact stated here
// (sub-processor list, retention periods, data residency, lawful bases)
// is drawn directly from that document — nothing invented. The one gap
// (ICO registration number) is left as an explicit placeholder rather
// than fabricated, since Nodus Limited is not yet registered (confirmed
// directly with Gokul during Session 14) — Session 13's log established
// the project's standing rule against inventing data that doesn't exist.
export const metadata = {
  title: "Privacy Policy | Autopilot",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-page-bg px-5 py-10">
      <div className="mx-auto max-w-[720px]">
        <Link href="/login" className="text-secondary text-nhs-blue">
          ← Back to sign in
        </Link>

        <div className="mt-4 rounded-card border border-border-default bg-card-bg p-8">
          <h1 className="text-page-heading text-text-primary">Privacy Policy</h1>
          <p className="mt-1 text-secondary text-text-secondary">Last updated: 31 August 2026</p>

          <div className="mt-6 space-y-6 text-body text-text-primary">
            <section>
              <h2 className="text-section-heading text-text-primary">1. Who we are</h2>
              <p className="mt-2">
                Autopilot is provided by Nodus Limited, a company registered in the United
                Kingdom (Company Director: Gokul).
              </p>
              <p className="mt-2 text-text-secondary">
                ICO registration number: [pending — Nodus Limited will complete ICO registration
                before this policy applies to any real, non-trial customer data].
              </p>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">2. What data we collect</h2>
              <p className="mt-2">We collect and process three broad categories of data:</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>
                  <strong>Account data</strong> — names, email addresses, phone numbers, and role
                  information for managers, carers, and family members using Autopilot.
                </li>
                <li>
                  <strong>Care records</strong> — the service user data your organisation enters,
                  including care plans, visit logs, medication records, incident reports, and
                  related health and welfare information.
                </li>
                <li>
                  <strong>Usage data</strong> — technical logs (IP addresses, request logs)
                  generated by using the platform.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">3. Why we collect it</h2>
              <p className="mt-2">
                Care records — including health conditions, medication records, and care needs —
                are <strong>special category personal data</strong> under UK GDPR Article 9. We
                process this data under Article 6(1)(b) (necessary for the performance of the
                care contract between the service user and your organisation) together with
                Article 9(2)(h) (necessary for the provision of health or social care).
              </p>
              <p className="mt-2">
                Account and contact data for managers, carers, and family members is processed
                under Article 6(1)(b) — necessary for the performance of the service contract.
              </p>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">4. Who we share it with</h2>
              <p className="mt-2">
                We use the following sub-processors to deliver Autopilot. Each is contractually
                bound to only process data for the stated purpose.
              </p>
              <div className="mt-3 overflow-x-auto">
                <table className="w-full min-w-[520px] border-collapse text-secondary">
                  <thead>
                    <tr className="border-b border-border-default text-left">
                      <th className="py-1.5 pr-4">Sub-processor</th>
                      <th className="py-1.5 pr-4">Data received</th>
                      <th className="py-1.5 pr-4">Purpose</th>
                      <th className="py-1.5">Location</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      ["Supabase", "All personal data", "Database, authentication, file storage", "UK (eu-west-2)"],
                      ["Anthropic", "Contextual data only (see below)", "AI feature generation", "USA"],
                      ["Netlify", "IP addresses, request logs", "Hosting, content delivery", "USA (global edge)"],
                      ["Stripe", "Billing name, email, payment method", "Subscription billing", "USA/EU"],
                      ["Resend", "Email address, email body", "Transactional email", "USA"],
                    ].map((row) => (
                      <tr key={row[0]} className="border-b border-border-default">
                        {row.map((cell, i) => (
                          <td key={i} className="py-1.5 pr-4">
                            {cell}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="mt-3">
                Where our AI features are used, only aggregated, contextual data is sent to
                Anthropic (e.g. visit counts, compliance percentages, first names where needed for
                a summary to make sense). We never send NHS numbers, full addresses, dates of
                birth, financial data, full record IDs, or family member contact details.
                Anthropic does not use this data to train its models.
              </p>
              <p className="mt-2">
                We will notify your organisation of any change to this sub-processor list with 30
                days&apos; notice by email, as required under UK GDPR.
              </p>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">5. Where we store it</h2>
              <p className="mt-2">
                All personal data is stored exclusively on UK servers. Our database and file
                storage both run on Supabase infrastructure in AWS&apos;s London region
                (eu-west-2), set at the time our account was created and unable to be changed.
                Backups are stored in the same region.
              </p>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">6. How long we keep it</h2>
              <div className="mt-3 overflow-x-auto">
                <table className="w-full min-w-[480px] border-collapse text-secondary">
                  <thead>
                    <tr className="border-b border-border-default text-left">
                      <th className="py-1.5 pr-4">Data type</th>
                      <th className="py-1.5">Retention period</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      ["Active client records", "Indefinitely, while the client is active"],
                      ["Archived client records", "7 years after archiving"],
                      ["Visit logs and eMAR records", "7 years from the record date"],
                      ["Incident records", "7 years from the incident date"],
                      ["Staff records", "7 years after deactivation"],
                      ["Audit logs", "7 years from creation"],
                      ["Invoices", "7 years from invoice date"],
                      ["Messages", "3 years from creation"],
                      ["Data after account cancellation", "90 days, then permanently deleted"],
                    ].map((row) => (
                      <tr key={row[0]} className="border-b border-border-default">
                        <td className="py-1.5 pr-4">{row[0]}</td>
                        <td className="py-1.5">{row[1]}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">7. Your rights</h2>
              <p className="mt-2">Under UK GDPR, you have the right to:</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>Access the personal data we (via your care provider) hold about you</li>
                <li>Have inaccurate data corrected</li>
                <li>Request erasure of your data</li>
                <li>Restrict how your data is processed</li>
                <li>Receive your data in a portable format</li>
                <li>Object to processing</li>
              </ul>
              <p className="mt-2">
                If you are a service user, family member, or member of staff, these requests are
                handled by the care provider organisation you interact with — they are the data
                controller for your information. Autopilot (Nodus Limited) provides the tools
                (including full data export) that let them fulfil these rights, and will assist
                a care provider in doing so on request.
              </p>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">8. How to contact us</h2>
              <p className="mt-2">
                For questions about this policy or how Nodus Limited processes data, contact us
                at{" "}
                <a href="mailto:support@noduslimited.co.uk" className="text-nhs-blue">
                  support@noduslimited.co.uk
                </a>
                .
              </p>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">9. How to complain</h2>
              <p className="mt-2">
                If you are unhappy with how your data has been handled, you can complain to the
                Information Commissioner&apos;s Office (ICO), the UK&apos;s data protection
                regulator, at{" "}
                <a
                  href="https://ico.org.uk/make-a-complaint/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-nhs-blue"
                >
                  ico.org.uk/make-a-complaint
                </a>
                .
              </p>
            </section>

            <section>
              <h2 className="text-section-heading text-text-primary">10. Changes to this policy</h2>
              <p className="mt-2">
                We may update this policy from time to time. Material changes will be notified to
                registered organisations by email with at least 30 days&apos; notice before they
                take effect.
              </p>
            </section>
          </div>
        </div>

        <p className="mt-4 text-center text-tiny text-text-secondary">
          Autopilot is a product of Nodus Limited. noduslimited.co.uk
        </p>
      </div>
    </div>
  );
}
