-- Source: Gokul, direct request 2026-09-03 — Rota page full redesign (item 8).
-- Adds recurrence support to rota_shifts so "Add shift" can generate a
-- linked series (daily/weekly/custom) instead of one row at a time.
-- No change to rota_shifts_staff_date_key (still one shift ENVELOPE per
-- carer per day) — the redesign's "multiple client visits stacked in
-- time order" is rendered from the existing visits table (already
-- carries its own per-client scheduled_start/scheduled_end, generated by
-- ensureVisitsForShift), not from a schema change to rota_shifts itself.

alter table rota_shifts
  add column recurrence text not null default 'once'
    check (recurrence in ('once', 'daily', 'weekly', 'custom')),
  add column recurrence_group_id uuid null;

create index rota_shifts_recurrence_group_idx
  on rota_shifts (recurrence_group_id)
  where recurrence_group_id is not null;
